### ISSUE TITLE
separate drag node and drag svg

### ISSUE THREAD

**Issue by remyla** [PRIMCODE/graphViewer#11]
handle svg drag and node drag gracefully (right now the svg drag occurs when dragging a node and it should not)
please have a look at this example:

http://jsfiddle.net/blt909/aVhd8/20/

**Comment by jogal360** [comment]
@MatLala please have a look
please have a look: http://jogal360.github.io/graphViewer/

**Comment by MatLala** [comment]
Thanks @jogal360. Works fine !
You can do a pull request.
